CC = c++
FLAGS = -Wall -Wextra -Werror -std=c++98
NAME = violence

SRC = HumanA.cpp \
		HumanB.cpp \
		Weapon.cpp \
		main.cpp

OBJ = $(SRC:.cpp=.o) 

all: $(NAME)

$(NAME): $(OBJ)
		$(CC) $(FLAGS) -o $(NAME) $(OBJ)

%.o: %.cpp
		$(CC) $(FLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re